version: "3.8"


services:
  broker:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: pythonclub
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    depends_on:
      - "broker"

  database_init:
    build: .
    entrypoint: python3
    command:
      - src/__main__.py
      - db
    depends_on:
      - "database"

  meaning_parser:
    build: .
    entrypoint: python3
    command:
      - src/__main__.py
      - def
    depends_on:
      - "database_init"

  word_parser:
    build: .
    entrypoint: python3
    command:
      - src/__main__.py
      - words
    depends_on:
      - "database_init"

  bot_engine:
    build: .
    entrypoint: python3
    command:
      - src/__main__.py
      - bot
    depends_on:
      - "database_init"

  notification_manager:
    build: .
    entrypoint: python3
    command:
      - src/__main__.py
      - notification_manager
    depends_on:
      - "bot_engine"